# Generated by Django 3.0.6 on 2020-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='comment',
            field = models.CharField(max_length = 300, null = True)
        ),
        migrations.AddField(
            model_name='films',
            name='description',
            field = models.CharField (max_length = 100, null = True)
        ),
        migrations.AddField(
            model_name='films',
            name='limits',
            field = models.TextField(max_length = 3000, null = True)
        ),
        migrations.AddField(
            model_name='films',
            name='site',
            field = models.TextField(max_length = 3000, null = True)
        ),
    ]
