# Generated by Django 3.0.6 on 2020-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200527_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='comment',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='limits',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='site',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
