# Generated by Django 3.0.6 on 2020-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200527_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='imdb_id',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='IMDb идентификатор'),
        ),
    ]
