# Generated by Django 3.0.6 on 2020-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200529_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='film',
            field=models.IntegerField(db_index=True, null=True, verbose_name='KID'),
        ),
    ]
