# Generated by Django 3.0.6 on 2020-05-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200531_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='evaluation',
            field=models.IntegerField(verbose_name='Идентификатор оценки пользователя'),
        ),
    ]
