# Generated by Django 3.0.6 on 2020-05-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_likes_filmobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='evaluation',
            field=models.IntegerField(null=True, verbose_name='Идентификатор оценки пользователя'),
        ),
    ]
