# Generated by Django 3.0.6 on 2020-06-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '06_my'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsreleasedate',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Country'),
        ),
        migrations.AlterField(
            model_name='filmsreleasedate',
            name='format',
            field=models.CharField(choices=[('0', 'Обычный'), ('1', 'Фестиваль'), ('2', 'Limited'), ('3', 'DVD'), ('4', 'Blu-Ray'), ('5', 'Internet'), ('6', '3D'), ('7', 'Другой'), ('8', 'TV')], max_length=1, null=True, verbose_name='Формат релиза'),
        ),
        migrations.AlterField(
            model_name='films',
            name='name',
            field=models.ManyToManyField(null=True, to='base.NameFilms', verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='films',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
    ]
