# Generated by Django 3.0.6 on 2020-06-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '07'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmsreleasedate',
            options={'ordering': ['-release']},
        ),
    ]
